### PR TITLE
Add CSV export feature to 'Issues' table

### PR DESCRIPTION
**Pull request by rushenn**
Make sure to run `bower install` under `static/vendors` before test

screen shot 2018-08-09 at 16 24 09

### CODE REVIEW

**Comment by deekoder** [comment]
there are some spacing issues in the csv. But i think its because of office libre. Maybe fine on google sheets.

**Review by deekoder — APPROVED** [review]

**Comment by deekoder** [comment]
no longer needed.

**Comment by deekoder** [comment]
THought about it more today. Since its here already, no sense in not taking an improvement which is already completed.

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
